/*
 * TIMER1_cfg.h
 *
 *  Created on: Jul 19, 2019
 *      Author: Muhammad.Elzeiny
 */

#ifndef E15_REPO_SRC_CONFIG_TIMER1_CFG_H_
#define E15_REPO_SRC_CONFIG_TIMER1_CFG_H_
/*
 * TIMER1_PRESCALER_1_msk
 * TIMER1_PRESCALER_8_msk
 * TIMER1_PRESCALER_64_msk
 * TIMER1_PRESCALER_256_msk
 * TIMER1_PRESCALER_1024_msk
 * */
#define TIMER1_PRESCALER_SELECTOR		TIMER1_PRESCALER_256_msk

#define TIMER1_COMPARE_STEP_A			300
#define TIMER1_COMPARE_STEP_B			200
/**
 * TIMER1_MODE_NORMAL_msk
 * TIMER1_MODE_CTC_TOP_OCR1A_msk
 * TIMER1_MODE_CTC_TOP_ICR1_msk
 */
#define TIMER1_MODE_SELECTOR			TIMER1_MODE_CTC_TOP_ICR1_msk

/*
 * TIMER1_ICU_EDGE_RISING_msk
 * TIMER1_ICU_EDGE_FALLING_msk
 * */
#define TIMER1_ICU_EDGE_SELECTOR		TIMER1_ICU_EDGE_RISING_msk

#define TIMER1_INT_COMPA_EN				DISABLE
#define TIMER1_INT_COMPB_EN				DISABLE
#define TIMER1_INT_CAPT_EN				ENABLE
#define TIMER1_INT_OVF_EN				DISABLE
#endif /* E15_REPO_SRC_CONFIG_TIMER1_CFG_H_ */
